-- Generated by scripts/generate-schedules.ts from src/lib/jobs/registry.ts.
-- Do not edit: `npm run schedules:generate` after changing the registry.
--
-- Run this once per environment, AFTER storing the two secrets in Vault:
--
--   select vault.create_secret('https://gaopportunityledger.com', 'ledger_site_url');
--   select vault.create_secret('<the CRON_SECRET value>',        'ledger_cron_secret');
--
-- schedule_ledger_job() is defined in the migration that enables pg_cron; it is
-- idempotent, so re-running this file re-points existing schedules rather than
-- duplicating them.

select public.schedule_ledger_job(
  'publish-scheduled',
  '*/15 * * * *'
);

select public.schedule_ledger_job(
  'premium-alerts',
  '*/15 * * * *'
);

select public.schedule_ledger_job(
  'saved-search-matching',
  '*/30 * * * *'
);

select public.schedule_ledger_job(
  'process-exports',
  '*/5 * * * *'
);

select public.schedule_ledger_job(
  'evaluate-deadlines',
  '10 5 * * *'
);

select public.schedule_ledger_job(
  'deadline-reminders',
  '0 13 * * *'
);

select public.schedule_ledger_job(
  'reverification-reminders',
  '30 5 * * *'
);

select public.schedule_ledger_job(
  'stale-source-reminders',
  '40 5 * * *'
);

select public.schedule_ledger_job(
  'expire-lapsed-access',
  '20 5 * * *'
);

select public.schedule_ledger_job(
  'sync-subscriptions',
  '0 */6 * * *'
);

select public.schedule_ledger_job(
  'aggregate-analytics',
  '15 6 * * *'
);

select public.schedule_ledger_job(
  'prune',
  '45 6 * * *'
);

select public.schedule_ledger_job(
  'scan-attachments',
  '*/20 * * * *'
);

select public.schedule_ledger_job(
  'distribute-weekly-report',
  '0 12 * * 4'
);

-- Verify:
--   select jobname, schedule, active from cron.job order by jobname;
--   select * from cron.job_run_details order by start_time desc limit 20;
