// Generated by scripts/generate-schedules.ts from src/lib/jobs/registry.ts.
// Do not edit: `npm run schedules:generate` after changing the registry.
//
// Generates queued CSV exports.
// Schedule: */5 * * * * (UTC)

export default async function handler(): Promise<Response> {
  const base = process.env.URL ?? process.env.NEXT_PUBLIC_SITE_URL;
  const secret = process.env.CRON_SECRET;

  if (!base || !secret) {
    // Loud rather than silent: a scheduled function that quietly does nothing
    // looks exactly like one that ran and found no work.
    console.error(
      '[schedule] process-exports cannot run: URL or CRON_SECRET is not set',
    );
    return new Response('missing configuration', { status: 500 });
  }

  // Netlify does not attach the scheduler's credentials the way Vercel Cron
  // does, so the header is sent explicitly.
  const response = await fetch(`${base}/api/v1/jobs/process-exports`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${secret}` },
  });

  const body = await response.text();
  if (!response.ok) {
    console.error(
      '[schedule] process-exports failed',
      response.status,
      body.slice(0, 500),
    );
    return new Response(body, { status: response.status });
  }

  return new Response(body, { status: 200 });
}

export const config = { schedule: '*/5 * * * *' };
