/**
 * CSV generation for Premium exports (spec 10.7).
 *
 * Two things this module takes seriously that a naive `rows.join(',')` does
 * not:
 *
 *   - RFC 4180 quoting, so a summary containing a comma, quote or newline does
 *     not shift every subsequent column.
 *   - Formula injection. A cell beginning `=`, `+`, `-`, `@`, tab or carriage
 *     return is interpreted as a formula by Excel and Sheets, which turns an
 *     exported opportunity title into code that runs on the member's machine.
 *     Such cells are prefixed with an apostrophe, the standard mitigation.
 */

export const FORMULA_TRIGGERS = ['=', '+', '-', '@', '\t', '\r'];

export function escapeCell(value: unknown): string {
  if (value === null || value === undefined) return '';

  let text: string;
  if (value instanceof Date) {
    text = value.toISOString();
  } else if (typeof value === 'object') {
    text = JSON.stringify(value);
  } else {
    text = String(value);
  }

  const firstChar = text.charAt(0);
  if (text.length > 0 && FORMULA_TRIGGERS.includes(firstChar)) {
    text = `'${text}`;
  }

  if (/[",\n\r]/.test(text)) {
    return `"${text.replace(/"/g, '""')}"`;
  }
  return text;
}

export interface CsvColumn<T> {
  header: string;
  value: (row: T) => unknown;
}

export function toCsv<T>(rows: readonly T[], columns: readonly CsvColumn<T>[]): string {
  const lines: string[] = [];
  lines.push(columns.map((column) => escapeCell(column.header)).join(','));
  for (const row of rows) {
    lines.push(columns.map((column) => escapeCell(column.value(row))).join(','));
  }
  // CRLF per RFC 4180; Excel on Windows is the most common destination.
  return lines.join('\r\n') + '\r\n';
}

export interface ExportableOpportunity {
  title: string;
  slug: string;
  category: string;
  subtype: string;
  status: string;
  score: number;
  score_classification: string;
  county_name?: string | null;
  city_name?: string | null;
  street_address?: string | null;
  summary: string;
  estimated_value_min?: number | null;
  estimated_value_max?: number | null;
  capital_required_min?: number | null;
  capital_required_max?: number | null;
  closing_date?: string | null;
  date_verified?: string | null;
  verification_status: string;
  original_source_url: string;
  recommended_next_action: string;
  is_sample?: boolean;
}

export function opportunityExportColumns(
  siteUrl: string,
): CsvColumn<ExportableOpportunity>[] {
  return [
    { header: 'Title', value: (r) => r.title },
    { header: 'Category', value: (r) => r.category },
    { header: 'Subtype', value: (r) => r.subtype },
    { header: 'Status', value: (r) => r.status },
    { header: 'Score', value: (r) => r.score },
    { header: 'Classification', value: (r) => r.score_classification },
    { header: 'County', value: (r) => r.county_name ?? '' },
    { header: 'City', value: (r) => r.city_name ?? '' },
    { header: 'Address', value: (r) => r.street_address ?? '' },
    { header: 'Summary', value: (r) => r.summary },
    { header: 'Estimated value (min)', value: (r) => r.estimated_value_min ?? '' },
    { header: 'Estimated value (max)', value: (r) => r.estimated_value_max ?? '' },
    { header: 'Capital required (min)', value: (r) => r.capital_required_min ?? '' },
    { header: 'Capital required (max)', value: (r) => r.capital_required_max ?? '' },
    { header: 'Closing date', value: (r) => r.closing_date ?? '' },
    { header: 'Date verified', value: (r) => r.date_verified ?? '' },
    { header: 'Verification status', value: (r) => r.verification_status },
    { header: 'Source URL', value: (r) => r.original_source_url },
    { header: 'Recommended next action', value: (r) => r.recommended_next_action },
    { header: 'Sample data', value: (r) => (r.is_sample ? 'yes' : 'no') },
    {
      header: 'Ledger link',
      value: (r) => `${siteUrl.replace(/\/$/, '')}/opportunities/${r.slug}`,
    },
  ];
}

/**
 * Exports above this row count are generated by the background worker rather
 * than inline, so a large request cannot hold a request handler open past the
 * platform's timeout (spec 10.7, 23).
 */
export const ASYNC_EXPORT_THRESHOLD = 500;

export function shouldGenerateAsynchronously(rowCount: number): boolean {
  return rowCount > ASYNC_EXPORT_THRESHOLD;
}

export function exportFileName(prefix: string, now: Date = new Date()): string {
  const stamp = now.toISOString().slice(0, 19).replace(/[:T]/g, '-');
  const safePrefix = prefix
    .replace(/[^a-zA-Z0-9-_]/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+/, '')
    .slice(0, 40);
  return `${safePrefix || 'export'}-${stamp}.csv`;
}
