/**
 * Generates the platform scheduling config from `src/lib/jobs/registry.ts`.
 *
 *   npm run schedules:generate     # write
 *   npm run schedules:check        # fail if the committed files are stale
 *
 * The registry has always carried a comment saying the schedule lives there
 * "so that `vercel.json` and the runbook can be generated from one source
 * rather than drifting apart". Nothing generated anything; `vercel.json` was
 * maintained by hand, and when `scan-attachments` was added the two were
 * updated separately and happened to agree. Adding a second deployment target
 * makes that luck untenable — three copies of fourteen cron expressions is a
 * drift generator.
 *
 * So both are emitted from the registry, and `tests/unit/jobs/schedules.test.ts`
 * fails when the committed output no longer matches.
 *
 * `netlify.toml` is deliberately not generated: none of it derives from the
 * registry, and a generator that also owns hand-written config invites edits
 * that are silently overwritten.
 *
 * The two platforms differ in one way that matters. Vercel Cron calls the
 * route directly and attaches `CRON_SECRET` as a bearer token itself. Netlify
 * has no such convention: a scheduled function is ordinary code, so it has to
 * make the call and send the header. The job endpoint is unchanged either way
 * — it authorises on the header, not on who is calling.
 */

import {
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
  readdirSync,
} from 'node:fs';
import { join } from 'node:path';

import { format, resolveConfig } from 'prettier';

import { JOBS } from '../src/lib/jobs/registry';

const ROOT = join(import.meta.dirname, '..');
const NETLIFY_FUNCTIONS = join(ROOT, 'netlify', 'functions');
const VERCEL_CONFIG = join(ROOT, 'vercel.json');

const GENERATED_NOTE =
  '// Generated by scripts/generate-schedules.ts from src/lib/jobs/registry.ts.\n' +
  '// Do not edit: `npm run schedules:generate` after changing the registry.\n';

function vercelConfig(): string {
  return `${JSON.stringify(
    {
      $schema: 'https://openapi.vercel.sh/vercel.json',
      framework: 'nextjs',
      crons: JOBS.map((job) => ({
        path: `/api/v1/jobs/${job.definition.name}`,
        schedule: job.schedule,
      })),
    },
    null,
    2,
  )}\n`;
}

/**
 * One scheduled function per job.
 *
 * Netlify schedules are declared per function, so there is no way to express
 * fourteen different cadences in one. Each file is deliberately tiny and does
 * nothing but call the job endpoint — the job logic stays in one place and
 * runs identically on both platforms.
 */
function netlifyFunction(
  name: string,
  schedule: string,
  description: string,
): string {
  return `${GENERATED_NOTE}//
// ${description}
// Schedule: ${schedule} (UTC)

export default async function handler(): Promise<Response> {
  const base = process.env.URL ?? process.env.NEXT_PUBLIC_SITE_URL;
  const secret = process.env.CRON_SECRET;

  if (!base || !secret) {
    // Loud rather than silent: a scheduled function that quietly does nothing
    // looks exactly like one that ran and found no work.
    console.error(
      '[schedule] ${name} cannot run: URL or CRON_SECRET is not set',
    );
    return new Response('missing configuration', { status: 500 });
  }

  // Netlify does not attach the scheduler's credentials the way Vercel Cron
  // does, so the header is sent explicitly.
  const response = await fetch(\`\${base}/api/v1/jobs/${name}\`, {
    method: 'POST',
    headers: { Authorization: \`Bearer \${secret}\` },
  });

  const body = await response.text();
  if (!response.ok) {
    console.error('[schedule] ${name} failed', response.status, body.slice(0, 500));
    return new Response(body, { status: response.status });
  }

  return new Response(body, { status: 200 });
}

export const config = { schedule: '${schedule}' };
`;
}

/**
 * Output goes through Prettier before it is written.
 *
 * `format:check` runs over the whole repository in CI, so generated files have
 * to satisfy it too. Formatting here rather than adding an ignore rule means
 * the generated code stays readable, and an edit to a template cannot quietly
 * make the repository unformattable.
 */
async function generate(): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  // `filepath` alone only picks the parser. The repository's own options —
  // including the Tailwind class-sorting plugin — come from .prettierrc, so
  // they have to be resolved explicitly or the output fails `format:check`.
  const pretty = async (path: string, contents: string) => {
    const options = (await resolveConfig(path)) ?? {};
    files.set(path, await format(contents, { ...options, filepath: path }));
  };

  await pretty(VERCEL_CONFIG, vercelConfig());

  for (const job of JOBS) {
    await pretty(
      join(NETLIFY_FUNCTIONS, `${job.definition.name}.ts`),
      netlifyFunction(
        job.definition.name,
        job.schedule,
        job.definition.description,
      ),
    );
  }
  return files;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const files = await generate();
  let stale = 0;

  if (!check) {
    mkdirSync(NETLIFY_FUNCTIONS, { recursive: true });
    // Remove functions for jobs that no longer exist, or a deleted job keeps
    // firing against an endpoint that now 404s.
    for (const existing of readdirSync(NETLIFY_FUNCTIONS)) {
      const path = join(NETLIFY_FUNCTIONS, existing);
      if (!files.has(path)) {
        rmSync(path);
        console.log(`removed ${existing} (no longer in the registry)`);
      }
    }
  }

  for (const [path, contents] of files) {
    let current: string | null = null;
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      current = null;
    }

    if (current === contents) continue;

    if (check) {
      console.error(`stale: ${path.replace(`${ROOT}/`, '')}`);
      stale += 1;
    } else {
      writeFileSync(path, contents);
      console.log(`wrote ${path.replace(`${ROOT}/`, '')}`);
    }
  }

  if (check && stale > 0) {
    console.error(
      `\n${stale} file(s) do not match the registry. ` +
        'Run `npm run schedules:generate`.',
    );
    process.exit(1);
  }
  if (check) console.log(`${files.size} scheduling files match the registry.`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
